# Copyright (c) 2026 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Flash Attention v4 unified public interface.

Exposes the framework-specific backend through a single stable import path:

    from flash_mask.interface import flash_attn_func, flash_attn_varlen_func

The backend is fixed at **install time** via the ``FLASH_ATTN_BACKEND``
environment variable passed to ``pip install`` / ``setup.py``:

    FLASH_ATTN_BACKEND=paddle pip install -e . --no-build-isolation   # default
    FLASH_ATTN_BACKEND=torch  pip install -e . --no-build-isolation

The chosen value is baked into ``flash_mask/_backend.py`` by ``setup.py``.
No environment variable is needed (or checked) at runtime.
"""

import importlib
import paddle
from .cute.interface import flashmask_attention as _cute_flashmask_attention

__all__ = [
    "flash_attn_func",
    "flash_attn_varlen_func",
    "flash_attn_combine",
    "flash_attention",
    "flashmask_attention",
]

_BACKENDS = {
    "paddle": "flash_mask.flash_attn_v4.paddle.interface",
    "torch":  "flash_mask.flash_attn_v4.torch.interface",
}

# ---------------------------------------------------------------------------
# Resolve backend name from compile-time _backend.py (generated by setup.py).
# Falls back to 'paddle' (matching setup.py default) if _backend.py is absent
# (e.g. running directly from a source checkout without pip install).
# ---------------------------------------------------------------------------
try:
    from flash_mask._backend import BACKEND as _backend_name
except ImportError:
    _backend_name = 'paddle'

if _backend_name not in _BACKENDS:
    raise ValueError(
        f"Unknown backend {_backend_name!r}, "
        f"expected one of {sorted(_BACKENDS)}"
    )

try:
    _mod = importlib.import_module(_BACKENDS[_backend_name])
except ImportError as e:
    raise ImportError(
        f"Backend {_backend_name!r} is not available. "
        f"Re-install with FLASH_ATTN_BACKEND={_backend_name} to confirm, "
        f"or switch backend via FLASH_ATTN_BACKEND at install time."
    ) from e

flash_attn_func        = _mod.flash_attn_func
flash_attn_varlen_func = _mod.flash_attn_varlen_func
flash_attn_combine     = _mod.flash_attn_combine

def convert_to_varlen(
    query: paddle.Tensor,
    key: paddle.Tensor,
    value: paddle.Tensor,
    startend_row_indices: paddle.Tensor,
    causal: bool,
):
    b, sq, hq, d = query.shape
    _, skv, hkv, dv = value.shape
    assert sq == skv

    _, hfm, _, bound_num = startend_row_indices.shape
    assert hfm == 1
    assert bound_num == 1 or bound_num == 2

    # ── Extract document boundaries PER BATCH from startend_row_indices ──
    # startend_row_indices shape: (batch, nheads_fm, seqlen_k, bound_num)
    # Column 0 encodes the "end of document" boundary for each key position.
    # Tokens within the same document share the same value; boundaries are
    # where this value changes.  Different batch items may have different
    # document layouts, so we extract boundaries for each batch independently.
    s = startend_row_indices[:, 0, :, 0]  # (batch, seqlen_k)

    cu_seqlens_parts = []
    max_doc_len = 0
    needs_padding_fixup = False
    real_ends = []

    for bi in range(b):
        s_bi = s[bi]  # (seqlen_k,)

        # Find change positions -> document boundaries
        diff_bi = paddle.not_equal(s_bi[1:], s_bi[:-1])
        change_idx_bi = paddle.nonzero(diff_bi).flatten().cast(paddle.int32) + 1

        # Real end of documents (max value in column 0)
        real_end_bi = int(s_bi.max().item())
        real_ends.append(real_end_bi)
        if real_end_bi < skv:
            needs_padding_fixup = True

        # Boundaries: [0, change_1, ..., seqlen_k]
        # Always use seqlen_k as last boundary so padding KV (visible to
        # the last doc's rows in flashmask) is included in the last doc.
        boundaries_bi = paddle.concat([
            paddle.zeros([1], dtype=paddle.int32),
            change_idx_bi,
            paddle.to_tensor([skv], dtype=paddle.int32),
        ])

        # Track max document length across all batches
        doc_lens_bi = boundaries_bi[1:] - boundaries_bi[:-1]
        max_doc_len = max(max_doc_len, int(doc_lens_bi.max().item()))

        # Collect document start positions with batch offset
        cu_seqlens_parts.append(boundaries_bi[:-1] + bi * skv)

    # Build cu_seqlens: concat per-batch starts + final endpoint
    cu_seqlens = paddle.concat(
        cu_seqlens_parts + [paddle.to_tensor([b * skv], dtype=paddle.int32)]
    )

    # ── Flatten q, k, v: (batch, seqlen, heads, dim) -> (total, heads, dim)
    q_varlen = query.reshape([b * sq, hq, d])
    k_varlen = key.reshape([b * skv, hkv, d])
    v_varlen = value.reshape([b * skv, hkv, dv])

    # ── Detect simulated causal masks ──────────────────────────────────
    # A causal document mask can be encoded as causal=False with bound_num=2
    # (LTS + UTE) where UTE[j] = min(j, LTS[j]) reproduces the causal
    # diagonal.  For true non-causal masks, UTE is constant within each
    # document (= document start), which differs from min(j, LTS[j]).
    varlen_causal = causal
    bound_num = startend_row_indices.shape[-1]
    if not causal and bound_num == 2:
        lts_all = startend_row_indices[:, 0, :, 0]  # (b, skv)
        ute_all = startend_row_indices[:, 0, :, 1]  # (b, skv)
        arange_ref = paddle.arange(skv, dtype=paddle.int32).unsqueeze(0)  # (1, skv)
        expected_causal_ute = paddle.minimum(arange_ref, lts_all)  # (b, skv)
        if paddle.equal_all(ute_all, expected_causal_ute).item():
            varlen_causal = True

    result = {
        "q": q_varlen,
        "k": k_varlen,
        "v": v_varlen,
        "cu_seqlens_q": cu_seqlens,
        "cu_seqlens_k": cu_seqlens,
        "max_seqlen_q": max_doc_len,
        "max_seqlen_k": max_doc_len,
        "causal": varlen_causal,
    }

    # For non-causal masks with trailing padding: padding rows attend to
    # nothing in flashmask (zero output), but varlen computes non-zero
    # output for them.  Zero out padding rows per batch to match flashmask.
    # Note: real_end can differ across batch items.
    if needs_padding_fixup:
        _b, _sq = b, sq
        _real_ends = real_ends

        def output_to_padded(out_varlen_pt):
            nh = out_varlen_pt.shape[1]
            dv_out = out_varlen_pt.shape[2]
            out_padded = out_varlen_pt.reshape(_b, _sq, nh, dv_out)
            # Vectorised per-batch zeroing
            row_idx = paddle.arange(_sq)
            real_end_t = paddle.to_tensor(
                _real_ends, dtype=paddle.int64,
            ).unsqueeze(1)
            padding_mask = row_idx.unsqueeze(0) >= real_end_t  # (b, sq)
            out_padded[padding_mask] = 0
            return out_padded

        result["output_to_padded"] = output_to_padded

    return result

def flashmask_attention(
    query: paddle.Tensor,
    key: paddle.Tensor,
    value: paddle.Tensor,
    startend_row_indices: paddle.Tensor | None = None,
    *,
    dropout: float = 0.0,
    causal: bool = False,
    window_size: int | tuple | None = None,
    return_softmax_lse: bool = False,
    return_seed_offset: bool = False,
    fixed_seed_offset: paddle.Tensor | None = None,
    rng_name: str = "",
    training: bool = True,
    name: str | None = None,
    softmax_scale: float | None = None,
    block_mask: paddle.Tensor | None = None,
    use_varlen: bool = False,
):
    if use_varlen:
        assert (
            paddle.base.framework.get_flags(["FLAGS_flash_attn_version"])["FLAGS_flash_attn_version"] == 4
        ), (
            "use_varlen only support fa4"
        )
        batch_size, seqlen_q, nheads, _ = query.shape
        dv = value.shape[-1]
        varlen_args = convert_to_varlen(
            query=query,
            key=key,
            value=value,
            startend_row_indices=startend_row_indices,
            causal=causal)
        out, lse = flash_attn_varlen_func(
            q=varlen_args["q"],
            k=varlen_args["k"],
            v=varlen_args["v"],
            cu_seqlens_q=varlen_args["cu_seqlens_q"],
            cu_seqlens_k=varlen_args["cu_seqlens_k"],
            max_seqlen_q=varlen_args["max_seqlen_q"],
            max_seqlen_k=varlen_args["max_seqlen_k"],
            causal=varlen_args["causal"],
            return_lse=return_softmax_lse,
        )

        if "output_to_padded" in varlen_args:
            out = varlen_args["output_to_padded"](out)
        else:
            out = out.reshape([batch_size, seqlen_q, nheads, dv])

        if return_softmax_lse:
            return [out, lse]
        else:
            return out
    else:
        return _cute_flashmask_attention(
            query=query,
            key=key,
            value=value,
            startend_row_indices=startend_row_indices,
            dropout=dropout,
            causal=causal,
            window_size=window_size,
            return_softmax_lse=return_softmax_lse,
            return_seed_offset=return_seed_offset,
            fixed_seed_offset=fixed_seed_offset,
            rng_name=rng_name,
            training=training,
            name=name,
            softmax_scale=softmax_scale,
            block_mask=block_mask,
        )
