# Copyright (c) 2026 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Flash Attention v4 unified public interface.

Exposes the framework-specific backend through a single stable import path:

    from flash_mask.interface import flash_attn_func, flash_attn_varlen_func

The backend is fixed at **install time** via the ``FLASH_ATTN_BACKEND``
environment variable passed to ``pip install`` / ``setup.py``:

    FLASH_ATTN_BACKEND=paddle pip install -e . --no-build-isolation   # default
    FLASH_ATTN_BACKEND=torch  pip install -e . --no-build-isolation

The chosen value is baked into ``flash_mask/_backend.py`` by ``setup.py``.
No environment variable is needed (or checked) at runtime.
"""

import importlib
import numpy as np
import paddle
from .cute.interface import flashmask_attention as _cute_flashmask_attention

__all__ = [
    "flash_attn_func",
    "flash_attn_varlen_func",
    "flash_attn_combine",
    "flash_attention",
    "flashmask_attention",
]

_BACKENDS = {
    "paddle": "flash_mask.flash_attn_v4.paddle.interface",
    "torch":  "flash_mask.flash_attn_v4.torch.interface",
}

# ---------------------------------------------------------------------------
# Resolve backend name from compile-time _backend.py (generated by setup.py).
# Falls back to 'paddle' (matching setup.py default) if _backend.py is absent
# (e.g. running directly from a source checkout without pip install).
# ---------------------------------------------------------------------------
try:
    from flash_mask._backend import BACKEND as _backend_name
except ImportError:
    _backend_name = 'paddle'

if _backend_name not in _BACKENDS:
    raise ValueError(
        f"Unknown backend {_backend_name!r}, "
        f"expected one of {sorted(_BACKENDS)}"
    )

try:
    _mod = importlib.import_module(_BACKENDS[_backend_name])
except ImportError as e:
    raise ImportError(
        f"Backend {_backend_name!r} is not available. "
        f"Re-install with FLASH_ATTN_BACKEND={_backend_name} to confirm, "
        f"or switch backend via FLASH_ATTN_BACKEND at install time."
    ) from e

flash_attn_func        = _mod.flash_attn_func
flash_attn_varlen_func = _mod.flash_attn_varlen_func
flash_attn_combine     = _mod.flash_attn_combine

def convert_to_varlen(
    query: paddle.Tensor,
    key: paddle.Tensor,
    value: paddle.Tensor,
    startend_row_indices: paddle.Tensor,
    causal: bool,
):
    b, sq, hq, d = query.shape
    _, skv, hkv, dv = value.shape
    assert sq == skv

    _, hfm, _, bound_num = startend_row_indices.shape
    assert hfm == 1
    assert bound_num == 1 or bound_num == 2

    # ── Move startend_row_indices to numpy (single GPU→CPU transfer) ──
    sri_np = startend_row_indices.numpy()  # (batch, hfm, seqlen_k, bound_num)
    s_np = sri_np[:, 0, :, 0]  # (batch, seqlen_k)

    # ── Vectorised boundary detection in numpy ──
    # Compare consecutive elements per batch: (b, skv-1)
    diffs = s_np[:, 1:] != s_np[:, :-1]

    # Real ends per batch
    real_ends_np = s_np.max(axis=1)  # (b,)

    # Per-batch boundary extraction (b is typically 1-2, loop is trivial)
    cu_seqlens_q_list = []
    cu_seqlens_k_list = []
    max_doc_len_q = 0
    max_doc_len_k = 0
    for bi in range(b):
        change_idx = np.nonzero(diffs[bi])[0].astype(np.int32) + 1
        boundaries = np.concatenate([
            np.zeros(1, dtype=np.int32),
            change_idx,
            np.array([skv], dtype=np.int32),
        ])
        real_end = int(real_ends_np[bi])

        if real_end < skv:
            # Has padding: only include real documents, then add two
            # padding documents at tail.
            # Find the boundary index where padding starts
            real_boundaries = boundaries[boundaries <= real_end]
            if real_boundaries[-1] != real_end:
                real_boundaries = np.concatenate([
                    real_boundaries, np.array([real_end], dtype=np.int32)
                ])

            doc_lens = real_boundaries[1:] - real_boundaries[:-1]
            max_doc_len_q = max(max_doc_len_q, int(doc_lens.max()))
            max_doc_len_k = max(max_doc_len_k, int(doc_lens.max()))

            pad_len = skv - real_end

            # cu_seqlens_q: [...real_doc_starts, real_end, real_end, real_end+pad_len]
            #   -> docs: real docs, then (0 seqlen_q, pad_len seqlen_k), then (pad_len seqlen_q, 0 seqlen_k)
            # cu_seqlens_k: [...real_doc_starts, real_end, real_end+pad_len, real_end+pad_len]
            offset = np.int32(bi * skv)
            cu_seqlens_q_list.append(np.concatenate([
                real_boundaries[:-1] + offset,
                np.array([real_end, real_end], dtype=np.int32) + offset,
            ]))
            cu_seqlens_k_list.append(np.concatenate([
                real_boundaries[:-1] + offset,
                np.array([real_end, real_end + pad_len], dtype=np.int32) + offset,
            ]))

            max_doc_len_k = max(max_doc_len_k, pad_len)
            max_doc_len_q = max(max_doc_len_q, pad_len)
        else:
            # No padding
            doc_lens = boundaries[1:] - boundaries[:-1]
            max_doc_len_q = max(max_doc_len_q, int(doc_lens.max()))
            max_doc_len_k = max(max_doc_len_k, int(doc_lens.max()))
            cu_seqlens_q_list.append(boundaries[:-1] + np.int32(bi * skv))
            cu_seqlens_k_list.append(boundaries[:-1] + np.int32(bi * skv))

    # Build cu_seqlens: one numpy concat, one paddle tensor creation
    cu_seqlens_q_np = np.concatenate(
        cu_seqlens_q_list + [np.array([b * skv], dtype=np.int32)]
    )
    cu_seqlens_k_np = np.concatenate(
        cu_seqlens_k_list + [np.array([b * skv], dtype=np.int32)]
    )
    cu_seqlens_q = paddle.to_tensor(cu_seqlens_q_np)
    cu_seqlens_k = paddle.to_tensor(cu_seqlens_k_np)

    # ── Flatten q, k, v: (batch, seqlen, heads, dim) -> (total, heads, dim)
    q_varlen = query.reshape([b * sq, hq, d])
    k_varlen = key.reshape([b * skv, hkv, d])
    v_varlen = value.reshape([b * skv, hkv, dv])

    # ── Detect simulated causal masks (numpy) ────────────────────────
    varlen_causal = causal
    if not causal and bound_num == 2:
        lts_all = s_np  # (b, skv), already extracted
        ute_all = sri_np[:, 0, :, 1]  # (b, skv)
        arange_ref = np.arange(skv, dtype=np.int32).reshape(1, skv)
        expected_causal_ute = np.minimum(arange_ref, lts_all)
        if np.array_equal(ute_all, expected_causal_ute):
            varlen_causal = True

    result = {
        "q": q_varlen,
        "k": k_varlen,
        "v": v_varlen,
        "cu_seqlens_q": cu_seqlens_q,
        "cu_seqlens_k": cu_seqlens_k,
        "max_seqlen_q": max_doc_len_q,
        "max_seqlen_k": max_doc_len_k,
        "causal": varlen_causal,
    }

    return result

def flashmask_attention(
    query: paddle.Tensor,
    key: paddle.Tensor,
    value: paddle.Tensor,
    startend_row_indices: paddle.Tensor | None = None,
    *,
    dropout: float = 0.0,
    causal: bool = False,
    window_size: int | tuple | None = None,
    return_softmax_lse: bool = False,
    return_seed_offset: bool = False,
    fixed_seed_offset: paddle.Tensor | None = None,
    rng_name: str = "",
    training: bool = True,
    name: str | None = None,
    softmax_scale: float | None = None,
    block_mask: paddle.Tensor | None = None,
    use_varlen: bool = False,
):
    if use_varlen:
        assert (
            paddle.base.framework.get_flags(["FLAGS_flash_attn_version"])["FLAGS_flash_attn_version"] == 4
        ), (
            "use_varlen only support fa4"
        )
        assert dropout == 0, (
            "use_varlen does not support dropout"
        )
        assert window_size is None, (
            "use_varlen does not support setting window_size"
        )
        assert block_mask is None, (
            "use_varlen does not support block_mask"
        )

        batch_size, seqlen_q, nheads, d = query.shape
        seqlen_k = key.shape[1]
        assert seqlen_q == seqlen_k, (
            f"use_varlen requires seqlen_q == seqlen_k, ",
            f"currently seqlen_q={seqlen_q}, seqlen_k={seqlen_k}",
        )

        dv = value.shape[-1]

        if (d == 256 or dv == 256):
            assert not return_softmax_lse, (
                "SM100 backward with head_dim=256 does not support dlse, ",
                "please set return_softmax_lse to False"
            )

        varlen_args = convert_to_varlen(
            query=query,
            key=key,
            value=value,
            startend_row_indices=startend_row_indices,
            causal=causal)
        out, lse = flash_attn_varlen_func(
            q=varlen_args["q"],
            k=varlen_args["k"],
            v=varlen_args["v"],
            cu_seqlens_q=varlen_args["cu_seqlens_q"],
            cu_seqlens_k=varlen_args["cu_seqlens_k"],
            max_seqlen_q=varlen_args["max_seqlen_q"],
            max_seqlen_k=varlen_args["max_seqlen_k"],
            softmax_scale=softmax_scale,
            causal=varlen_args["causal"],
            return_lse=return_softmax_lse,
        )

        out = out.reshape([batch_size, seqlen_q, nheads, dv])

        if return_softmax_lse:
            return [out, lse]
        else:
            return out
    else:
        return _cute_flashmask_attention(
            query=query,
            key=key,
            value=value,
            startend_row_indices=startend_row_indices,
            dropout=dropout,
            causal=causal,
            window_size=window_size,
            return_softmax_lse=return_softmax_lse,
            return_seed_offset=return_seed_offset,
            fixed_seed_offset=fixed_seed_offset,
            rng_name=rng_name,
            training=training,
            name=name,
            softmax_scale=softmax_scale,
            block_mask=block_mask,
        )
